server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test
    username: postgres
    password: password

open:
  api:
    serverUrl: http://localhost:${server.port}
    serverName: Server TEST
